services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mohaymen
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  migrate:
    image: yaghooli/dotnetdev:latest
    command: ["./migrateout"]  
    depends_on:
      - postgres
    environment:
      CONNECTION_STRING: Host=postgres;Database=mohaymen;Username=postgres;Password=1234;
  
  admin:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8089:8080

  web:
    image: yaghooli/dotnetdev:latest
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CONNECTION_STRING: Host=postgres;Database=mohaymen;Username=postgres;Password=1234;
    ports:
      - "8085:80"

volumes:
  pgdata:

