//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalysisData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnalysisData.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an admin!.
        /// </summary>
        internal static string AdminExistenceException {
            get {
                return ResourceManager.GetString("AdminExistenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not delete or modify admin information !.
        /// </summary>
        internal static string AdminProtectedException {
            get {
                return ResourceManager.GetString("AdminProtectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This category already exists!.
        /// </summary>
        internal static string CategoryAlreadyExist {
            get {
                return ResourceManager.GetString("CategoryAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category does not exist in our system!.
        /// </summary>
        internal static string CategoryResultNotFoundException {
            get {
                return ResourceManager.GetString("CategoryResultNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We already have this role in the database!.
        /// </summary>
        internal static string DuplicateRoleException {
            get {
                return ResourceManager.GetString("DuplicateRoleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have a user with this information!.
        /// </summary>
        internal static string DuplicateUserException {
            get {
                return ResourceManager.GetString("DuplicateUserException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge not found!.
        /// </summary>
        internal static string EdgeNotFoundException {
            get {
                return ResourceManager.GetString("EdgeNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Operation ! .
        /// </summary>
        internal static string FailedOpetaionException {
            get {
                return ResourceManager.GetString("FailedOpetaionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We already have this file!.
        /// </summary>
        internal static string FileExistenceException {
            get {
                return ResourceManager.GetString("FileExistenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to processing file ! .
        /// </summary>
        internal static string FileProcessingException {
            get {
                return ResourceManager.GetString("FileProcessingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID format is invalid!.
        /// </summary>
        internal static string GuidNotCorrectFormatException {
            get {
                return ResourceManager.GetString("GuidNotCorrectFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header(s) not found in the uploaded file: {0}.
        /// </summary>
        internal static string HeaderIdNotFoundInNodeFile {
            get {
                return ResourceManager.GetString("HeaderIdNotFoundInNodeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format!.
        /// </summary>
        internal static string InvalidEmailFormatException {
            get {
                return ResourceManager.GetString("InvalidEmailFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is invalid!.
        /// </summary>
        internal static string InvalidPasswordException {
            get {
                return ResourceManager.GetString("InvalidPasswordException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password format is invalid!.
        /// </summary>
        internal static string InvalidPasswordFormatException {
            get {
                return ResourceManager.GetString("InvalidPasswordFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number format!.
        /// </summary>
        internal static string InvalidPhoneNumberFormatException {
            get {
                return ResourceManager.GetString("InvalidPhoneNumberFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no edges found for this node ! .
        /// </summary>
        internal static string NodeHasNotEdgesException {
            get {
                return ResourceManager.GetString("NodeHasNotEdgesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header(s) Node is not accessible for this user! {0}.
        /// </summary>
        internal static string NodeNotAccessibleForUserException {
            get {
                return ResourceManager.GetString("NodeNotAccessibleForUserException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node was not found!.
        /// </summary>
        internal static string NodeNotFoundException {
            get {
                return ResourceManager.GetString("NodeNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodes with IDs {0} were not found!.
        /// </summary>
        internal static string NodeNotFoundInEntityEdgeException {
            get {
                return ResourceManager.GetString("NodeNotFoundInEntityEdgeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file uploaded!.
        /// </summary>
        internal static string NoFileUploadedException {
            get {
                return ResourceManager.GetString("NoFileUploadedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password is null!.
        /// </summary>
        internal static string PasswordHasherInputNull {
            get {
                return ResourceManager.GetString("PasswordHasherInputNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not match!.
        /// </summary>
        internal static string PasswordMismatchException {
            get {
                return ResourceManager.GetString("PasswordMismatchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We do not have this role!.
        /// </summary>
        internal static string RoleNotFoundException {
            get {
                return ResourceManager.GetString("RoleNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token expired!.
        /// </summary>
        internal static string TokenExpiredException {
            get {
                return ResourceManager.GetString("TokenExpiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Invalid ! .
        /// </summary>
        internal static string TokenIsInvalidException {
            get {
                return ResourceManager.GetString("TokenIsInvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token not found in cookies!.
        /// </summary>
        internal static string TokenNotFoundInCookieException {
            get {
                return ResourceManager.GetString("TokenNotFoundInCookieException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found!.
        /// </summary>
        internal static string UserNotFoundException {
            get {
                return ResourceManager.GetString("UserNotFoundException", resourceCulture);
            }
        }
    }
}
